CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    UserName VARCHAR(15) NOT NULL,
    UserPassword NVARCHAR(100) NOT NULL,
    Email VARCHAR(20) NOT NULL,
	CreationDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE PasswordHistory (
    UserID INT PRIMARY KEY FOREIGN KEY (UserID) REFERENCES Users,
    OldPassword NVARCHAR(100) NOT NULL,
    ChangeDate DATETIME DEFAULT GETDATE(),
);

CREATE TABLE PasswordSalts (
    SaltID INT PRIMARY KEY IDENTITY(1,1),
	UserID INT FOREIGN KEY (UserID) REFERENCES Users,
    PasswordSalts NVARCHAR(100) NOT NULL,  
);